config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #nav
  root 'home#index', as:'home'

  get '/contact', to:'home#contact',as:'contact'
  get '/support', to:'home#support',as:'support'
  get '/about', to:'home#about',as:'about'
  #/article/new

  #TODO change add_blog to new
  get '/article/new', to:'article#new', as:'article_new'
  post '/article/new', to:'article#create', as:'article_create'
  get '/article/show/:id', to:'article#show', as:'article_show'
  #delete
  delete '/article/delete/:id', to:'article#delete', as:'article_delete'
  #update
  get '/article/edit/:id',to:'article#edit', as:'article_edit'
  patch '/article/edit/:id',to:'article#update',as:'article_update'

  #sessions
  get '/login', to:'sessions#login',as:'login'
  post '/login', to:'sessions#new', as:'user_new'
  get '/signup',to:'sessions#signup',as:'signup'
  post '/signup',to:'sessions#create', as:'user_create'
  get '/logout', to:'sessions#logout', as:'logout'

  #account
  get '/account', to:'user_account#index', as:'account'
  delete '/account', to:'user_account#delete', as:'account_delete'

  #comments
  post '/comment/new', to:'comment#new',as:'comment_new'
  delete '/comment/delete/:id', to:'comment#delete', as:'comment_delete'

  #searching user
  get '/search/user/articles', to:'home#search_user', as:'search_user'

end

app/views/layout_temp/_footer.html.erb
<div class = 'container footer'>
  <div class="row fbg">
    <div class="col-sm-4">
      <h3><span>About</span></h3>
      <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum.
        Cras id urna. Morbi tincidunt, orci ac convallis aliquam, lectus turpis varius lorem, eu posuere
        nunc justo tempus leo. llorem, eu posuere nunc justo tempus leo. Donec mattis, purus nec placerat
        bibendum. <%= link_to 'Learn more...', about_path%></p>
    </div>
    <div class="col-sm-4">
      <h3 class="star"><span>Categories</span></h3>
      <ul class="list-group list-group-flush sb_menu ft_cat">
        <li class = "list-group-item"><a href="#">Education</a></li>
        <li class = "list-group-item"><a href="#">Entertainment</a></li>
        <li class = "list-group-item"><a href="#">Sports</a></li>
        <li class = "list-group-item"><a href="#">Fashion</a></li>
        <li class = "list-group-item"><a href="#">News</a></li>
      </ul>
    </div>
    <div class="col-sm-4">
      <h3>Contact</h3>
      <p>Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue.</p>
      <p><a href="#">support@yoursite.com</a></p>
      <p>+1 (123) 444-5677<br />
        +1 (123) 444-5678</p>
      <p>Address: 123 TemplateAccess Rd1</p>
    </div>
  </div>
</div>

app/views/layout_temp/_nav.html.erb
<div class = 'container-fluid' id = 'nav'>
  <nav class="navbar navbar-default navbar-inverse" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Home', home_path, class:"navbar-brand home" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Add Article', article_new_path, class:'addArticle' %></li>
          <li><%= link_to 'About', about_path,class:'about' %></li>
          <li><%= link_to 'Contact', contact_path,class:'contact' %></li>
          <li><%= link_to 'Support', support_path ,class:'support'%></li>

        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li>
              <%= link_to account_path do %>
                <%= current_user.username %>
              <% end %>
            </li>
            <li>
              <%= link_to logout_path do %>
                <span class="glyphicon glyphicon-log-out"></span> Logout
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to signup_path do %>
                <span class="glyphicon glyphicon-user"></span> Sign Up
              <% end %>
            </li>
            <li>
              <%= link_to login_path do %>
                <span class="glyphicon glyphicon-log-in"></span> Login
              <% end %>
            </li>
          <% end %>
        </ul>
        <%= form_with(url: search_user_path, :class => 'navbar-form navbar-left', method: :get) do |form| %>
          <div class='input-group'>
            <%= form.text_field :username, class:'form-control', placeholder:'search articles of a user' %>
            <div class = "input-group-btn">
              <%= form.submit 'find', class:'btn btn-default' %>
            </div>
          </div>
        <% end %>
        <!-- <form class="navbar-form navbar-left">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="search articles of a user" name="username">
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit">
                  <i class="glyphicon glyphicon-search"></i>
              </button>
            </div>
          </div>
        </form> -->

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</div>

app/views/layout_temp/_sidebar.html.erb
<div class = 'container' id = 'mainContainer'>
  <div class = 'row'>
    <% #content %>
    <div class = 'col-sm-9' id = 'content'>
      <%= yield %>
    </div>
     <% #sidebar %>
    <div class = 'col-sm-3'>
      <div class="gadget">
        <h3 class="star"><span>Categories</span></h3>
        <ul class="list-group list-group-flush sb_menu">
          <li class = "list-group-item"><a href="#">Education</a></li>
          <li class = "list-group-item"><a href="#">Entertainment</a></li>
          <li class = "list-group-item"><a href="#">Sports</a></li>
          <li class = "list-group-item"><a href="#">Fashion</a></li>
          <li class = "list-group-item"><a href="#">News</a></li>
        </ul>
      </div>
      <div class="gadget">
        <h3 class="star"><span>Recent Blogs</span></h3>
        <ul class="list-group recent_menu">
        <% @articles_side.each do |article| %>
          <li class='list-group-item'> <!-- article_show_path(article.id) -->
            <%= link_to "#{article.title}", article_show_path(article.id) %><br />
            <span class='subHeading'>November 2021 | posted by <%= User.find(article.user_id).username %></span>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>