config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #nav
  root 'home#index', as:'home'

  get '/contact', to:'home#contact',as:'contact'
  get '/support', to:'home#support',as:'support'
  get '/about', to:'home#about',as:'about'
  #/article/new

  #TODO change add_blog to new
  get '/article/new', to:'article#new', as:'article_new'
  post '/article/new', to:'article#create', as:'article_create'
  get '/article/show/:id', to:'article#show', as:'article_show'
  #delete
  delete '/article/delete/:id', to:'article#delete', as:'article_delete'
  #update
  get '/article/edit/:id',to:'article#edit', as:'article_edit'
  patch '/article/edit/:id',to:'article#update',as:'article_update'

  #sessions
  get '/login', to:'sessions#login',as:'login'
  post '/login', to:'sessions#new', as:'user_new'
  get '/signup',to:'sessions#signup',as:'signup'
  post '/signup',to:'sessions#create', as:'user_create'
  get '/logout', to:'sessions#logout', as:'logout'

  #account
  get '/account', to:'user_account#index', as:'account'
  delete '/account', to:'user_account#delete', as:'account_delete'

  #comments
  post '/comment/new', to:'comment#new',as:'comment_new'
  delete '/comment/delete/:id', to:'comment#delete', as:'comment_delete'

  #searching user
  get '/search/user/articles', to:'home#search_user', as:'search_user'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @articles = Article.paginate(page: params[:page], per_page:10).order('created_at DESC')
  end

  def search_user
    redirect_to home_path
    # logger.info "******************************search user is getting called"
    # user = User.find_by_username(params[:username])
    # if user
    #   @articles = Article.where(:user_id => user.id).paginate(page: params[:page], per_page:10).order('created_at DESC')
    #   render :index
    # else
    #   flash.now[:alert] = 'No such user exits!'
    #   @articles = nil
    #   render :index
    # end
  end

  def about
  end
  def contact

  end
  def support
  end
end

=begin
<% @articles.limit(3).order('created_at DESC').each do |article| %>
  <li>
    <%= link_to do %>
       <%= article.title %>
    <% end %>
  </li>
<% end %>
=end



=begin

<%= form_with(local:true,class:'navbar-form navbar-left') do |form| %>
  <div class="input-group">
    <%= form.text_field :username, class:'form-control', placeholder:'search' %>
  </div>
  <div class="input-group-btn">
    #TODO how to add btn btn-default class when using <%= form.submit do %>
    <%= form.submit do %>
      <i class="glyphicon glyphicon-search"></i>
    <% end %>
  </div>
<% end %>

=end


#https://intense-dawn-71889.herokuapp.com/

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="mainbar">
  <div class="article">
    <h2><span>About to</span> Company Name</h2>
    <div class="clr"></div>
    <p><strong>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eget bibendum tellus. Nunc vel imperdiet tellus. Mauris ornare aliquam urna, accumsan bibendum eros auctor ac.</strong></p>
    <p>Curabitur purus mi, pharetra vitae viverra et, mattis sit amet nunc. Quisque enim ipsum, convallis sit amet molestie in, placerat vel urna. Praesent congue auctor elit, nec pretium ipsum volutpat vitae. Vivamus eget ipsum sit amet ipsum tincidunt fermentum. Sed hendrerit neque ac erat condimentum vulputate. Nulla velit massa, dictum etinterdum quis, tempus at velit.</p>
  </div>
  <div class="article">
    <h2><span>Our</span> Mission</h2>
    <div class="clr"></div>
    <p><strong>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eget bibendum tellus. Nunc vel imperdiet tellus. Mauris ornare aliquam urna, accumsan bibendum eros auctor ac.</strong></p>
    <p>Maecenas vestibulum fermentum eleifend. Mauris erat sem, suscipit non tincidunt quis, vestibulum eget elit. Duis eget arcu ante. Proin nulla elit, elementum sit amet commodo et, eleifend vitae quam. Nam vel aliquam tortor. Aliquam bibendum erat a urna interdum quis mattis augue interdum. Phasellus fermentum bibendum mauris, ut semper justo pharetra vestibulum. Duis dictum purus sed nibh commodo a congue elit lobortis. Nunc sed feugiat tellus. Mauris aliquet lorem non enim euismod quis fermentum erat porta. Nullam non elit orci. Aliquam blandit mattis feugiat. Cras pulvinar aliquet massa, quis laoreet mi pulvinar ac. Aliquam mi augue, vehicula in consectetur in, porttitor sed tellus. Mauris convallis dapibus auctor. Integer in egestas lorem. In nulla dolor, sollicitudin vitae sollicitudin quis, viverra at lorem.</p>
    <p>Ut ullamcorper velit et nisi feugiat non sagittis tortor pharetra. Mauris ut urna et magna commodo cursus. Curabitur quis elementum arcu. Maecenas eleifend, urna vitae vehicula bibendum, felis tellus tincidunt lorem, at iaculis neque eros ac dui. Nunc malesuada pulvinar suscipit. Phasellus sed tortor quis ligula facilisis aliquam. Aliquam quis magna eu dolor posuere malesuada. Quisque consequat, metus fermentum convallis imperdiet, ante justo pharetra enim, vel commodo ipsum mauris eget purus. Morbi lacinia nisl urna, scelerisque suscipit lacus. Nulla ac orci ut nunc venenatis gravida.</p>
  </div>
</div>
<style>
.about {
  background-color: white;
}
</style>

app/views/home/contact.html.erb
<div class="article">
  <h2><span>Contact</span></h2>
  <div class="clr"></div>
  <p>You can find more of my free template designs at my website. For premium commercial designs, you can check out DreamTemplate.com.</p>
</div>
<div class="article">
  <h2><span>Send us</span> mail</h2>
  <%= form_with do |form| %>
    <div class = 'form-group'>
      <label>Name (Required)</label>
      <%= form.text_field :name, class:'form-control' %>
    </div>
    <div class = 'form-group'>
      <label>Email Address (Required)</label>
      <%= form.email_field :email, class:'form-control' %>
    </div>
    <div class = 'form-group'>
      <label>Message (Required)</label>
      <%= form.text_area :message, class:'form-control', id:'contactMessage' %>
    </div>
    <%= form.submit 'submit', class:'btn btn-default' %>
  <% end %>
</div>
<style>
#contactMessage {
  height:150px;
}
.contact {
  background-color: white;
}
</style>

app/views/home/index.html.erb
<!-- START PAGE SOURCE -->
<!-- notice message -->
<p class="text-success"><%= notice %></p>
<p class="text-danger"><%= alert %></p>

<% if @articles %>
  <% @articles.each do |article| %>
    <div class="article">
      <h3><%= article.title %></h3>
      <p>
        <span class="date">March 16, 2021</span> &nbsp;|&nbsp; Posted by
        <a href="#"><%= User.find(article.user_id).username %></a>
      </p>
      <p class='article-content'><%= article.content %></p>
      <p class="spec">
        <%= link_to 'read more..', article_show_path(article.id) %>
        &nbsp;|&nbsp;<%= link_to "comments (#{Comment.where(article_id: article.id).count})", article_show_path(article.id) %>
        <% if current_user && current_user.id == article.user_id %>
           &nbsp;|&nbsp;<%= link_to "edit", article_edit_path(article.id) %>
           &nbsp;|&nbsp;<%= link_to "delete", article_delete_path(article.id), method: :delete, data: {confirm:'Are you sure?'}%>
        <% end %>
      </p>
    </div>
  <% end %>
  <%= will_paginate @articles %>
<% end %>


<style>
.home {
  background-color: white;
}
.article-content {
  max-height:100px;
  overflow:hidden;
}
</style>

app/views/home/support.html.erb
<div class="article">
  <h2><span>Support to</span> Company Name</h2>
  <div class="clr"></div>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Suspendisse nulla ligula, blandit ultricies aliquet ac, lobortis in massa. Nunc dolor sem, tincidunt vitae viverra in, egestas sed lacus.</strong> Etiam in ullamcorper felis. Nulla cursus feugiat leo, ut dictum metus semper a. Vivamus euismod, arcu gravida sollicitudin vestibulum, quam sem tempus quam, quis ullamcorper erat nunc in massa. Donec aliquet ante non diam sollicitudin quis auctor velit sodales. Morbi neque est, posuere at fringilla non, mollis nec nibh. Sed commodo tortor nec sem tincidunt mattis. Nam convallis aliquam nibh eu luctus. Nunc vel tincidunt lacus. Suspendisse sit amet pulvinar ante.</p>
  <p>Phasellus diam justo, laoreet vel vulputate eu, congue vel est. Maecenas eros libero, sollicitudin a vulputate fermentum, ultrices vel lacus. Nam in metus non augue fermentum consequat ultrices ac enim. Integer aliquam urna non diam aliquam eget hendrerit sem molestie.</p>
  <p><strong>Lorem ipsum dolor sit amet</strong></p>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eget bibendum tellus. Nunc vel imperdiet tellus. Mauris ornare aliquam urna, accumsan bibendum eros auctor ac.</p>
  <ul class="">
    <li><a href="#"><strong>Lorem ipsum</strong></a></li>
    <li><a href="#"><strong>Lorem ipsum</strong></a></li>
    <li><a href="#"><strong>Lorem ipsum</strong></a></li>
    <li><a href="#"><strong>Lorem ipsum</strong></a></li>
    <li><a href="#"><strong>Lorem ipsum</strong></a></li>
    <li><a href="#"><strong>Lorem ipsum</strong></a></li>
  </ul>
</div>
<style>
.support {
  background-color: white;
}
</style>