config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #nav
  root 'home#index', as:'home'

  get '/contact', to:'home#contact',as:'contact'
  get '/support', to:'home#support',as:'support'
  get '/about', to:'home#about',as:'about'
  #/article/new

  #TODO change add_blog to new
  get '/article/new', to:'article#new', as:'article_new'
  post '/article/new', to:'article#create', as:'article_create'
  get '/article/show/:id', to:'article#show', as:'article_show'
  #delete
  delete '/article/delete/:id', to:'article#delete', as:'article_delete'
  #update
  get '/article/edit/:id',to:'article#edit', as:'article_edit'
  patch '/article/edit/:id',to:'article#update',as:'article_update'

  #sessions
  get '/login', to:'sessions#login',as:'login'
  post '/login', to:'sessions#new', as:'user_new'
  get '/signup',to:'sessions#signup',as:'signup'
  post '/signup',to:'sessions#create', as:'user_create'
  get '/logout', to:'sessions#logout', as:'logout'

  #account
  get '/account', to:'user_account#index', as:'account'
  delete '/account', to:'user_account#delete', as:'account_delete'

  #comments
  post '/comment/new', to:'comment#new',as:'comment_new'
  delete '/comment/delete/:id', to:'comment#delete', as:'comment_delete'

  #searching user
  get '/search/user/articles', to:'home#search_user', as:'search_user'

end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true

  belongs_to :user
  has_many :comment, dependent: :destroy

  def telling
    puts "are we entering into this"
  end
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
  def new
    if current_user
      @article = Article.new
    else
      redirect_to login_path, notice: 'You are not logged in!'
    end
  end

  def show
    #TODO what if id does not exits
    @article = Article.find(params[:id])
    #TODO what is all the model comment getting printed
    @comments = Comment.where(article_id: params[:id])
  end

  def create
    @article = Article.new(article_params)
    respond_to do |format|
      if @article.save
        format.html {redirect_to article_show_path(:id => @article.id), notice:'Article was successfully created!'}
        format.json {render :show, status: :created, location:@article}
      else
        format.html {render :new, status: :unprocessable_entity}
        format.json {render json: @article.errors, status: :unprocessable_entity }
        #byebug
      end
    end
  end

  def delete
    @article = Article.find(params[:id])
    #byebug
    @article.destroy
    respond_to do |format|
      format.html {redirect_to home_url, notice:'Article was successfully deleted'}
      format.json {head:no_content}
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_show_path(:id => @article.id), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def article_params
    params.require(:article).permit(:title, :content, :user_id)
  end
end

app/views/article/_form.html.erb
<div class = 'container-fluid'>
  <%= form_with(model: article, url: action_path, local:true) do |form| %>
    <% if article.errors.any? %>
      <h4><%= pluralize(article.errors.count, "error") %> prohibited this user from being saved:</h4>
      <% article.errors.full_messages.each do |message| %>
        <ul>
          <li><%= message %></li>
        </ul>
      <% end %>
    <% end %>
    <div class ='form-group'>
      <%= form.label 'Title' %>
      <%= form.text_field :title,class:'form-control' %>
    </div>
    <div class ='form-group'>
      <%= form.label 'Content'%>
      <%= form.text_area :content,class:'form-control', rows:13, id:'articleContent' %>
    </div>
    <div hidden>
      <%= form.number_field :user_id, value:current_user.id %>
    </div>
    <%= form.submit 'post',class:'btn btn-default'%>
  <% end %>
</div>

app/views/article/edit.html.erb
<%= render 'form', article: @article, action_path:article_update_path %>

app/views/article/new.html.erb
<%= render 'form', article:@article,action_path:article_new_path %>
<style>
.addArticle {
  background-color: white;
}
</style>

app/views/article/show.html.erb
<p class="text-success"><%= notice %></p>

<h3><%= @article.title %></h3>

<p><%= @article.content %></p>

<p>
  <span class="date article-sub">March 16, 2021  &nbsp;|&nbsp; Posted by
    <a href="#"><%= User.find(@article.user_id).username %></a>
  </span>
</p>

<p>
  <% if current_user && current_user.id == @article.user_id %>
     <%= link_to "edit", article_edit_path(@article.id) %>
     &nbsp;|&nbsp;<%= link_to "delete", article_delete_path(@article.id), method: :delete, data: {confirm:'Are you sure?'}%>
  <% end %>
</p>
<br />

<% if current_user %>
  <%= render 'comment/form', comment:Comment.new, article_id: @article.id, action_path:comment_new_path %>
<% else %>
  <p class="alert-danger">Please login to write a comment!</p>
<% end %>
<br />

<ul class='list-group'>
  <% if @comments %>
    <% @comments.each do |comment| %>
      <li class='list-group-item' style="border:none;"><%= comment.content %><br />
        <span class="subHeading">posted by : <%= User.find(comment.user_id).username %>
        <% if current_user && current_user.id == comment.user_id %>
          | <%= link_to 'Delete', comment_delete_path(comment.id), method: :delete, data: {confirm: 'Are you sure you want to delete your comment?'} %></span>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>